name: trepan3k (ubuntu)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Until the next xdis release
        pip install --local -e git+https://github.com/rocky/python-xdis.git#egg=xdis
        # Until the next pytracer release
        pip install git+https://github.com/rocky/pytracer#egg=tracer
        # Until the next pyficache release
        pip install git+https://github.com/rocky/python-filecache#egg=pyficache
        pip install -e .[dev]
    - name: Test trepan3k
      run: |
        make check
